hello

In [2]:
import pandas as pd

In [7]:
df = pd.read_parquet(r"D:\energy\mosques\mosque_violations_by_day.parquet")

In [8]:
df.head(5)

           METER_ID        date   Period  avg_power  readings  Violated
0  AEC2020720007045  2025-01-02  Evening   0.594000         7     False
1  AEC2020720007045  2025-01-02  Morning   0.195750         8     False
2  AEC2020720007045  2025-01-04  Evening   0.709429         7     False
3  AEC2020720007045  2025-01-04  Morning   0.179750         8     False
4  AEC2020720007045  2025-01-06  Evening   0.673714         7     False

In [10]:
dfin = pd.read_parquet(r"D:\energy\mosques\Industry Code with Population 1.parquet")
dfin.head(5)

,Meter Number,Premise,Installation,Contract Account,X Coordinates,Y Coordinates,Industry Sector,Business Partner,Name,Multiplication Factor,...,Department,Department Name,Office,Office Name,Province,POPULATION,HARA_NAME,PLACE_NAME,GOVERNORATE_NAME_AR,Shape_Area
0,ECC2020811088044,4000140860,5000121817,10001335779,50.160867,26.180090,Mosque,100132272,وزارة الشؤن الاسلامية/مسجد بورتبل .,1.00000,...,3100,ELECTRICITY ADMINISTRATION DAMMAM,3120,ALKHUBAR SERVICE OFFICE,EASTERN PROVINCE,20855,الصواري,الخبر,الخبر,0.001029
1,KFM2020660192535,4000542532,5000545847,10005466189,46.699344,24.556046,Mosque,100558961,وزارة الشئون الا سلا مية والااوقاف .,120.00000,...,1100,RIYADH ELECTRICITY SECTOR,1130,RIYADH CITY ELECTRICITY-SOUTH SERVICE OFFICE,RIYADH PROVINCE,70513,الشفا,الرياض,الرياض (مقر الامارة),0.000807
2,KFM2020660202496,4000536241,5000526091,10005534814,46.536884,24.569203,Mosque,100565478,وزارة الشئون الا سلا مية والااوقاف .,160.00000,...,1100,RIYADH ELECTRICITY SECTOR,1130,RIYADH CITY ELECTRICITY-SOUTH SERVICE OFFICE,RIYADH PROVINCE,282854,طويق,الرياض,الرياض (مقر الامارة),0.005421
3,KFM2020660200537,4000542039,5000545076,10005545175,46.668627,24.519298,Mosque,100563191,وزارة الشئون الا سلا مية والااوقاف .,60.00000,...,1100,RIYADH ELECTRICITY SECTOR,1130,RIYADH CITY ELECTRICITY-SOUTH SERVICE OFFICE,RIYADH PROVINCE,38410,عكاظ,الرياض,الرياض (مقر الامارة),0.001439
4,KFM2020660047193,4000548963,5000544928,10005563093,46.536076,24.560797,Mosque,100571224,وزارة الشئون الا سلا مية والااوقاف .,80.00000,...,1100,RIYADH ELECTRICITY SECTOR,1130,RIYADH CITY ELECTRICITY-SOUTH SERVICE OFFICE,RIYADH PROVINCE,282854,طويق,الرياض,الرياض (مقر الامارة),0.005421

In [11]:
dfin.columns

Index(['Meter Number', 'Premise', 'Installation', 'Contract Account',
       'X Coordinates', 'Y Coordinates', 'Industry Sector', 'Business Partner',
       'Name', 'Multiplication Factor', 'Device Type', 'Region', 'Department',
       'Department Name', 'Office', 'Office Name', 'Province', 'POPULATION',
       'HARA_NAME', 'PLACE_NAME', 'GOVERNORATE_NAME_AR', 'Shape_Area'],
      dtype='object')